### ISSUE TITLE
Add custom ggplot layer on top of fitRaster

### ISSUE THREAD

**Issue by dk-teknologisk-sven** [mfasiolo/mgcViz#79]
Is it possible to add a layer on top of a mgcViz-plot? Example:

```
library(mgcv)
library(mgcViz)
data= expand.grid(x=1:10,y=1:10)
set.seed(42)
data$val=rbinom(100, size = 1, prob = data$x*data$y/100)
gfit <- gam(val ~ s(x,y), data=data, family=binomial())
g <- getViz(gfit)

#This function plots the points underneath the plot(g) and therefore, it can't be seen
plot(g) + geom_point(data=data, aes(x=x,y=y, color=val), inherit.aes = F)
```
I would expect the above command to plot the points on top of the raster, but it doesn't
![example_plot](https://user-images.githubusercontent.com/90687467/171135216-c9bbccad-e7bf-419e-9068-65c3c22e928f.png)

**Comment by mfasiolo** [comment]
Hi, the problem is that `print.plotGam` will add a default `mgcViz` layer (in this case `l_fitRaster`) if none is present. And it will do so after you have added your layer, so the latter is masked. The solution is
```
plot(g) + l_fitRaster() + geom_point(data=data, aes(x=x,y=y, color=val), inherit.aes = F)
```
So by adding `l_fitRaster()` explicitly we avoid the masking problem. Note that the addition of default layers is also avoided by:
```
print(plot(g) + geom_point(data=data, aes(x=x,y=y, color=val), inherit.aes = F), addLay = FALSE)
```

**Comment by dk-teknologisk-sven** [comment]
That works! Thanks a lot :)
